#!/usr/local/bin/expect -f

set force_conservative 1  ;# set to 1 to force conservative mode even if
;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
			exp_send -s -- $arg
	}
}

set timeout -1
# Read title and content
set title_fd [open "title.txt"]
set title [read $title_fd]
set content_fd [open "content.txt"]
set content [read $content_fd]
## Set the boards you want to post in the following line, in its current form I'll post to "test" board
set boards [list test]
spawn telnet bs2.to
match_max 100000
expect "\[m   ¡° °ÑÆ\[±b¸¹¡G\[1;32mguest\[m  ¥ӽзs±b¸¹¡G\[1;31mnew\[m\[K\[37;15H"
## Set your credentials here
send -- "pellaeon\n"
send -- "passwd\n"
send -- "\r"
send -- "\r"
send -- "\r"
send -- "B"
send -- "\[C"
# Loop through boards
foreach board $boards {
	send -- "s"
	send -- $board
	send -- "\n"
	sleep 3
	send -- ""
	sleep 1
	send -- "6\n"
	sleep 1
	send -- $title
	sleep 1
	send -- $content
	sleep 1
	send -- ""
	send -- "s\n\n"
	send -- "\[D"
}
# Return control to the user
interact
